import { IconType } from "react-icons";
import { FaLayerGroup, FaDatabase, FaAws, FaSlack, FaWindows } from "react-icons/fa";
import {
  SiJavascript,
  SiTypescript,
  SiHtml5,
  SiCss,
  SiR,
  SiPhp,
  SiPython,
  SiSharp,
  SiCplusplus,
  SiOpenjdk,
  SiRust,
  SiGo,
  SiRuby,
  SiKotlin,
  SiSwift,
  SiDart,
  SiReact,
  SiNextdotjs,
  SiVuedotjs,
  SiNuxt,
  SiAngular,
  SiSvelte,
  SiTailwindcss,
  SiSass,
  SiLess,
  SiStyledcomponents,
  SiBootstrap,
  SiChakraui,
  SiMui,
  SiAntdesign,
  SiSemanticuireact,
  SiRedux,
  SiJquery,
  SiGatsby,
  SiRemix,
  SiAstro,
  SiThreedotjs,
  SiD3,
  SiChartdotjs,
  SiPlotly,
  SiFramer,
  SiNodedotjs,
  SiExpress,
  SiNestjs,
  SiDjango,
  SiFlask,
  SiSpring,
  SiSpringboot,
  SiLaravel,
  SiSymfony,
  SiCodeigniter,
  SiDotnet,
  SiRubyonrails,
  SiGraphql,
  SiSocketdotio,
  SiMysql,
  SiPostgresql,
  SiMongodb,
  SiSqlite,
  SiRedis,
  SiElasticsearch,
  SiApachekafka,
  SiRabbitmq,
  SiSupabase,
  SiPrisma,
  SiFirebase,
  SiVercel,
  SiNetlify,
  SiGooglecloud,
  SiDocker,
  SiKubernetes,
  SiJenkins,
  SiCircleci,
  SiGithubactions,
  SiGitlab,
  SiBitbucket,
  SiNginx,
  SiApache,
  SiUbuntu,
  SiDebian,
  SiCentos,
  SiRedhat,
  SiLinux,
  SiGit,
  SiGithub,
  SiFigma,
  SiPostman,
  SiInsomnia,
  SiSwagger,
  SiJira,
  SiTrello,
  SiNotion,
  SiNpm,
  SiYarn,
  SiPnpm,
  SiWebpack,
  SiVite,
  SiBabel,
  SiJson,
  SiYaml,
  SiMarkdown,
  SiWordpress,
  SiJest,
  SiCypress,
  SiSelenium,
  SiPytest,
  SiStorybook,
  SiNumpy,
  SiPandas,
  SiTensorflow,
  SiPytorch,
  SiScikitlearn,
  SiOpencv,
  SiFlutter,
  SiElectron,
  SiApple,
  SiAndroid,
  SiIos,
  SiUnity,
  SiUnrealengine,
  SiBlender,
} from "react-icons/si";

const iconMap: Record<string, IconType> = {
  javascript: SiJavascript,
  typescript: SiTypescript,
  html5: SiHtml5,
  html: SiHtml5,
  css3: SiCss,
  css: SiCss,
  r: SiR,
  php: SiPhp,
  python: SiPython,
  csharp: SiSharp,
  "c#": SiSharp,
  cplusplus: SiCplusplus,
  "c++": SiCplusplus,
  java: SiOpenjdk,
  rust: SiRust,
  go: SiGo,
  golang: SiGo,
  ruby: SiRuby,
  kotlin: SiKotlin,
  swift: SiSwift,
  dart: SiDart,
  react: SiReact,
  reactjs: SiReact,
  nextjs: SiNextdotjs,
  "next.js": SiNextdotjs,
  vuejs: SiVuedotjs,
  vue: SiVuedotjs,
  nuxt: SiNuxt,
  "nuxt.js": SiNuxt,
  angular: SiAngular,
  svelte: SiSvelte,
  tailwindcss: SiTailwindcss,
  "tailwind css": SiTailwindcss,
  sass: SiSass,
  scss: SiSass,
  less: SiLess,
  styledcomponents: SiStyledcomponents,
  "styled-components": SiStyledcomponents,
  bootstrap: SiBootstrap,
  chakraui: SiChakraui,
  "chakra ui": SiChakraui,
  mui: SiMui,
  "material ui": SiMui,
  antdesign: SiAntdesign,
  "ant design": SiAntdesign,
  semanticui: SiSemanticuireact,
  redux: SiRedux,
  jquery: SiJquery,
  gatsby: SiGatsby,
  remix: SiRemix,
  astro: SiAstro,
  threejs: SiThreedotjs,
  "three.js": SiThreedotjs,
  d3: SiD3,
  "d3.js": SiD3,
  chartjs: SiChartdotjs,
  "chart.js": SiChartdotjs,
  plotly: SiPlotly,
  framer: SiFramer,
  framermotion: SiFramer,
  nodejs: SiNodedotjs,
  "node.js": SiNodedotjs,
  express: SiExpress,
  expressjs: SiExpress,
  nestjs: SiNestjs,
  "nest.js": SiNestjs,
  django: SiDjango,
  flask: SiFlask,
  spring: SiSpring,
  springboot: SiSpringboot,
  "spring boot": SiSpringboot,
  laravel: SiLaravel,
  symfony: SiSymfony,
  codeigniter: SiCodeigniter,
  dotnetframework: SiDotnet,
  ".net framework": SiDotnet,
  dotnet: SiDotnet,
  ".net": SiDotnet,
  rubyonrails: SiRubyonrails,
  "ruby on rails": SiRubyonrails,
  graphql: SiGraphql,
  socketio: SiSocketdotio,
  "socket.io": SiSocketdotio,
  mysql: SiMysql,
  postgresql: SiPostgresql,
  postgres: SiPostgresql,
  mongodb: SiMongodb,
  sqlite: SiSqlite,
  redis: SiRedis,
  elasticsearch: SiElasticsearch,
  kafka: SiApachekafka,
  rabbitmq: SiRabbitmq,
  supabase: SiSupabase,
  prisma: SiPrisma,
  firebase: SiFirebase,
  oracledatabase: FaDatabase,
  "oracle database": FaDatabase,
  oracle: FaDatabase,
  sqlserver: FaDatabase,
  "sql server": FaDatabase,
  vercel: SiVercel,
  netlify: SiNetlify,
  aws: FaAws,
  "amazon web services": FaAws,
  googlecloud: SiGooglecloud,
  gcp: SiGooglecloud,
  docker: SiDocker,
  kubernetes: SiKubernetes,
  k8s: SiKubernetes,
  jenkins: SiJenkins,
  circleci: SiCircleci,
  githubactions: SiGithubactions,
  gitlab: SiGitlab,
  bitbucket: SiBitbucket,
  nginx: SiNginx,
  apache: SiApache,
  ubuntu: SiUbuntu,
  debian: SiDebian,
  centos: SiCentos,
  redhat: SiRedhat,
  linux: SiLinux,
  windows: FaWindows,
  git: SiGit,
  github: SiGithub,
  figma: SiFigma,
  postman: SiPostman,
  insomnia: SiInsomnia,
  swagger: SiSwagger,
  jira: SiJira,
  trello: SiTrello,
  notion: SiNotion,
  slack: FaSlack,
  npm: SiNpm,
  yarn: SiYarn,
  pnpm: SiPnpm,
  webpack: SiWebpack,
  vite: SiVite,
  babel: SiBabel,
  json: SiJson,
  yaml: SiYaml,
  markdown: SiMarkdown,
  wordpress: SiWordpress,
  jest: SiJest,
  cypress: SiCypress,
  selenium: SiSelenium,
  pytest: SiPytest,
  storybook: SiStorybook,
  numpy: SiNumpy,
  pandas: SiPandas,
  tensorflow: SiTensorflow,
  pytorch: SiPytorch,
  scikitlearn: SiScikitlearn,
  "scikit-learn": SiScikitlearn,
  opencv: SiOpencv,
  flutter: SiFlutter,
  electron: SiElectron,
  ios: SiIos,
  android: SiAndroid,
  macos: SiApple,
  unity: SiUnity,
  unrealengine: SiUnrealengine,
  "unreal engine": SiUnrealengine,
  blender: SiBlender,
};

export function getSkillIcon(skillName: string): IconType {
  const key = skillName.trim().toLowerCase();
  return iconMap[key] || FaLayerGroup;
}